modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/MC-U-Team/Useful-Railroads/issues"
displayURL="https://u-team.info/mods/usefulrailroads"
logoFile="logo.png"
credits="Team U-Team"
authors="HyCraftHD"

[[mods]]
	modId="usefulrailroads"
	version="${file.jarVersion}"
	displayName="Useful Railroads"
	updateJSONURL="https://api.u-team.info/update/usefulrailroads.json"
	description="Who don't want to travel fast? I do! So i created some high speed minecraft rails: Speed 100 blocks/second. This is just a very beta, cause I have many more plans for rails."
	
	[[dependencies.usefulrailroads]]
	    modId="forge"
	    mandatory=true
	    versionRange="[28.1.47,)"
	    ordering="NONE"
	    side="BOTH"
	
	[[dependencies.usefulrailroads]]
	    modId="minecraft"
	    mandatory=true
	    versionRange="[1.14.4]"
	    ordering="NONE"
	    side="BOTH"
	    
	[[dependencies.usefulrailroads]]
	    modId="uteamcore"
	    mandatory=true
	    versionRange="[2.7.4.134,)"
	    ordering="NONE"
	    side="BOTH"