modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/MC-U-Team/Useful-Railroads/issues"
displayURL="https://u-team.info/mods/usefulrailroads"
logoFile="logo.png"
credits="Team U-Team"
authors="HyCraftHD"

[[mods]]
	modId="usefulrailroads"
	version="${file.jarVersion}"
	displayName="Useful Railroads"
	updateJSONURL="https://api.u-team.info/update/usefulrailroads.json"
	description="Who don't want to travel fast? I do! So i created some high speed minecraft rails: Speed 100 blocks/second. There are also many other additions such as teleport rails, buffer stops and so on."
	
	[[dependencies.usefulrailroads]]
	    modId="forge"
	    mandatory=true
	    versionRange="[31.2.30,)"
	    ordering="NONE"
	    side="BOTH"
	
	[[dependencies.usefulrailroads]]
	    modId="minecraft"
	    mandatory=true
	    versionRange="[1.15.2]"
	    ordering="NONE"
	    side="BOTH"
	    
	[[dependencies.usefulrailroads]]
	    modId="uteamcore"
	    mandatory=true
	    versionRange="[3.0.2.169,)"
	    ordering="NONE"
	    side="BOTH"